### ISSUE TITLE
reason: 'couldn't find proto file'

### ISSUE THREAD

**Issue by nishal** [natep/Restless#7]
Keep getting this error on iOS where assertion fails at DRRestAdapter.m:102: reason: 'couldn't find proto file'

Any help appreciated. TIA

**Comment by natep** [comment]
Hey @nishal, the most common causes of this would be:
1. Your web service protocol does not inherit from DRWebService.
2. You have not added the necessary [Run Script Build Phase](https://github.com/natep/Restless/blob/master/README.md#installation).
3. Your protocol is not located in the app's main bundle. This can happen if you are exercising the code from a unit test.

For the last case, this can be fixed by specifying the correct bundle when creating the DRRestAdapter. You can see an example of this in the unit tests:

https://github.com/natep/Restless/blob/dd4eb1d77fa7ba90dc1093c16f783914444c6b26/RestlessTests/RestlessTests.m#L37

You would want to use a class that is located in the same bundle as your protocol.

If those suggestions don't fix your problem, then please paste in a copy of your protocol so I can take a look at it.

**Comment by nishal** [comment]
Thanks @natep it was 2 the script that I missed.
This is awesome. Now I have another problem, and I know that you don't support @FormUrlEncoded to send @POST parameters.
I'm guessing my best option is to create a class with members and use @Body like you have done in the User example, let me know if there is an easier way.

**Comment by natep** [comment]
@nishal I went ahead and implemented FormUrlEncoded. It's in version 0.0.6 that I just published.

**Comment by nishal** [comment]
@natep Thanks, appreciate the awesome update, will give it a try.

I'm curious on how you parse annotations and wondering if it is easily portable to Swift? I'm not a Swift developer, but enjoy using annotations in Java and can see how useful and powerful this can be with your Obj-C implementation in Restless.
